### ISSUE TITLE
demo无法运行

### ISSUE THREAD

**Issue by lantianhaijiao** [yylive/YYEVA-Web#1]
pnpm: 7.8.0
node: v14.17.2
报错如下
<img width="555" alt="image" src="https://user-images.githubusercontent.com/29088064/183235062-6a842856-a912-4dba-8d9d-a443c9cc4657.png">

**Comment by ckken** [comment]
根目录执行试试 需要构建完产物才能用
```js
{
    "dev": "pnpm --filter=yyeva --filter=offical dev",
    "build": "pnpm --filter=yyeva --filter=offical build",
    "start": "pnpm --filter=offical start"
  },
```
