### ISSUE TITLE
能否增加loop次数

### ISSUE THREAD

**Issue by mingyec** [yylive/YYEVA-Web#10]
希望能增加以下功能

1. loop 次数指定
2. 每次loop结束抛出指定事件

**Comment by ckken** [comment]
新版本 已经有了 @alexhaifeng

**Comment by alexhaifeng** [comment]
> 希望能增加以下功能
> 
> 1. loop 次数指定
> 2. 每次loop结束抛出指定事件

1. loop 指定次数已经支持
2. 每次loop结束抛出指定事件 --- 暂不支持

**Comment by alexhaifeng** [comment]
1.0.0-rc.14 
每次loop结束抛出指定事件: onLoopCount(args) // args: {count: 1}
