### ISSUE TITLE
播放访问不了的url(mp4) 会没有返回也没有onerror

### ISSUE THREAD

**Issue by winwingy** [yylive/YYEVA-Web#11]
![image](https://user-images.githubusercontent.com/17443657/204951457-2593f6c3-3797-4eb3-a4a2-f3c7e4a323a6.png)
如果这样， 比如我播一个访问的了的 xxxx.mp4 会完全没返回， 也不会onerror onend之类。 导致我没法判断是不是播放了，播放完了。

**Comment by doerme** [comment]
onerror 没有被正确触发，需要修复

**Comment by ckken** [comment]
![image](https://user-images.githubusercontent.com/3890513/205216454-54eea76a-e2a7-4dea-b6e5-09982d98f536.png)
<img width="460" alt="image" src="https://user-images.githubusercontent.com/3890513/205216485-89acd441-8dd7-4db0-bdbb-efddb024b225.png">
测试有触发 是否能提供一个在线 demo
