### ISSUE TITLE
可否辛苦加一下在window平台运行es5-demo的步骤和注意事项。

### ISSUE THREAD

**Issue by crazyit** [yylive/YYEVA-Web#13]
**问题描述**
因为日常工作机器在window上，下载了git源码后，在源码的根目录 执行pnpm install，然后切换到projects/es5-demo,执行pnpm run dev ，执行过程中各种报错
**截图**
![image](https://github.com/yylive/YYEVA-Web/assets/6240481/fc9c0c67-21cd-489e-9fdb-863c5eba81f8)

**客户端环境描述(请填写以下信息):**
 - 操作系统: window11

**附加消息**
尝试过在项目根目录和es5-demo目录 执行 pnpm add -D commander，依然无解。我猜测开发团队肯定是在mac平台开发，麻烦发点时间看下window平台的问题。谢谢，非常感谢！

**Comment by ckken** [comment]
感觉是权限问题 有在根目录执行 pnpm i 吗

**Comment by crazyit** [comment]
> 感觉是权限问题 有在根目录执行 pnpm i 吗

测试过，也是不行。不过我已经在win11 Ubuntu子系统里面跑通了这个demo，谢谢官方答复。
