### ISSUE TITLE
[1.0.2][web][运行直接报错]

### ISSUE THREAD

**Issue by XuanXiaoSa** [yylive/YYEVA-Web#21]
**问题描述**
升级1.0.2直接运行报错

**截图**
<img width="701" alt="image" src="https://github.com/yylive/YYEVA-Web/assets/18050722/c2f6d3ae-2403-4f13-8b5a-442223865818">

player.value = await yyEva({
        videoID: videoUrl,
        alphaDirection: 'left',
        mode: 'AspectFill',
        useMetaData: false,
        loop: false,
        autoplay: false,
        useFrameCache: false,
        useVideoDBCache: false,
        mute: false,
        forceBlob: true,
        showVideo: false,
        showPlayerInfo: false,
        useAccurate: false,
        usePrefetch: false,
        useBitmap: false,
        endPause: isEndPause,
        logLevel: 'debug',
        renderType: 'canvas2d',
        resizeCanvas: 'percentW',
        videoUrl,
        effects: {
          fontColor: '#000000'
        },
        container: videoDiv,

**附加消息**
额外补充一些和问题相关的信息。 

运行起来直接报错入上图

**Comment by alexhaifeng** [comment]
renderType: 'canvas2d', 这一行选项去掉还会报错吗？
