### ISSUE TITLE
[1.0.0-beta.26][Web]播放卡顿

### ISSUE THREAD

**Issue by mingyec** [yylive/YYEVA-Web#9]
**问题描述**
使用安卓机播放卡顿，原视频只有3s，不到100k的尺寸

**代码截图**
<img width="518" alt="image" src="https://user-images.githubusercontent.com/15625058/192782102-bc5e69f2-4c18-4b2b-b8e1-26185a0eb3a2.png">

**客户端环境描述(请填写以下信息):**
 - 操作系统: [e.g. iOS]
 - 浏览器 [e.g. chrome, safari]
 - 浏览器版本 [e.g. 22]

**手机环境 (请填写以下信息):**
 - 设备: [e.g. iPhone6]
 - 系统: [e.g. iOS8.1]
 - 浏览器 [e.g. stock browser, safari]
 - 浏览器版本 [e.g. 22]

**附加消息**
额外补充一些和问题相关的信息。

**Comment by ckken** [comment]
可以提供视频资源吗

**Comment by mingyec** [comment]
https://user-images.githubusercontent.com/15625058/194808742-be63f513-d0fd-4b9a-8d48-b8020a73e7ef.mp4

@ckken 可以使用这个来测试，我用的是红米note8，播放掉帧还是严重的

**Comment by ckken** [comment]
https://yyeva.yy.com/ 这个播放会出现卡顿么

**Comment by jack998628** [comment]
https://yyeva.yy.com/ 华为mate 50 打开之后动画会卡顿

**Comment by alexhaifeng** [comment]
请尝试播放参数设置 usePrefetch: false
